// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrzfikejvjinrgilozkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyemZpa2VqdmppbnJnaWxvemtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NzY0NDAsImV4cCI6MjA2NzE1MjQ0MH0.WW3PSPrG7BjLsLoGRMG34eeIt5A_XZIRv3LiW8W5w9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});